# Header
menu:
  Blog: /hexo-website/#blog
  About: /hexo-website/about
  Blogroll: /hexo-website/blogroll

# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png

# Enable Fancybox
fancybox: true
